### ISSUE TITLE
Using testing branch accroding to toltec/docs/branches.md seems to be not working

### ISSUE THREAD

**Issue by benjaminsoellner** [matteodelabre/toltec#377] opened 2021-06-23 23:28 UTC
Hello all!

I attempted to install the testing branch according to the specs defined here:
https://github.com/toltec-dev/toltec/blob/517d73c6bf23eae1afb6580f8a9890700e5bd141/docs/branches.md

> To use the testing branch, update the /opt/etc/opkg.conf file on an existing install or set the toltec_branch variable to testing when installing through the bootstrap script.

However, I get

![image](https://user-images.githubusercontent.com/12820910/123180304-5239e280-d48b-11eb-89c6-817404d99a08.png)

... and an HTTP 404 error for https://toltec-dev.org/testing/Packages.gz

![image](https://user-images.githubusercontent.com/12820910/123180363-6da4ed80-d48b-11eb-97cb-15f6191565b8.png)

Am I doing something wrong, does the docs need updating or is there an infrastructure issue?

Thanks!

**Comment by matteodelabre** [comment] 2021-06-24 10:02
Hi @benjaminsoellner, I think this is a duplicate of #341. In particular, check out this message for more details: https://github.com/toltec-dev/toltec/issues/341#issuecomment-819517368. If you have more questions, feel free to reply to this thread.

**Closed as completed by matteodelabre** 2021-06-24 10:02 UTC
Labels: duplicate
