### ISSUE TITLE
Error on line 60:

### ISSUE THREAD

**Issue by MN-company** [matteodelabre/toltec#433] opened 2021-09-17 17:39 UTC
INFO:  Fetching secure wget
ERROR: Unexpected error on line bootstrap:96 in function wget-bootstrap
ERROR: This script failed to install. If you can't solve the above
       issue yourself, please report it at:

           <https://github.com/toltec-dev/toltec/issues>

       (Please also include these error logs to help solving the
       problem faster. Thank you!)
bootstrap: line 60: clean-path: command not found

Can anyone help me plese?

**Comment by Eeems** [comment] 2021-09-17 18:06
What is the command you are running?

**Comment by MN-company** [comment] 2021-09-17 18:43
The second: 
echo  "9195122984700c76ccdc58e25d09d0fca486324e8fc55ba781f6e1b812cc186c  bootstrap" | sha256sum -c && bash bootstrap

**Comment by Eeems** [comment] 2021-09-17 19:36
And what is the first command you ran?

**Comment by matteodelabre** [comment] 2021-09-17 20:31
Duplicate of #422.

**Closed as completed by matteodelabre** 2021-09-17 20:31 UTC
Labels: duplicate, install
