### ISSUE TITLE
List supported OS versions in readme

### ISSUE THREAD

**Issue by jmcwine** [matteodelabre/toltec#486] opened 2021-11-01 07:21 UTC
Currently the information about supported OS versions is not easy to find.

**Comment by jmcwine** [comment] 2021-11-01 07:25
Perhaps the Toltec catalogue could also have a column which states the latest supported OS version for each package.

**Comment by LinusCDE** [comment] 2021-11-01 15:36
Hi jmcwine,

this idea a a good one, but I think we already decided and want to tackle this issue with #445. I also think, we had some discussion on alternative faster delivery of the version-dependant offsets for rm2fb (which are the major/most common thing holding back os support on the rM 2).

Any thoughts on this @matteodelabre , @Eeems ? Do we want to add this as well or treat it as a possible aspect of #445 ( = this issue being kinda related/a duplicate of that one)?

---

In general we intend to support each os asap. The only hurdle is, when the QT versions get changed, since we then need to update our toolchain to link properly again as well. This has happened once so far and a disclaimer would probably more appropriate at that point.  
The more common problem is, that all apps that need to draw on the display are dependant on a version-specific entry for rm2fb which is tracked here: https://github.com/ddvk/remarkable2-framebuffer/issues/18

**Comment by Eeems** [comment] 2021-11-01 16:42
I think this is good to include with #445, say the supported versions (including minimum, as we do technically drop support for older versions).

For toltec packages the big barrier to support as you mentioned is Qt and other library changes. When that happens we have to do a hard cut on support, or introduce new repositories supporting older versions. Luckily that doesn't happen too often.

For the rM2 the barrier for support is rm2fb. Unfortunately rm2fb support seems to lag longer than I'd like. https://github.com/ddvk/remarkable2-framebuffer/pull/79 is still sitting open with 2.10.2 support. Toltec can't technically support new versions until a new version of rm2fb is released, or until we start distributing our own version of the configuration file. This is what causes the most issues for us when an upgrade goes out.

**Comment by Eeems** [comment] 2023-08-18 01:56
I believe that at this point, the version information on the website, as well as the pending other work on enhancing toltecctl to provide feedback on if it's a supported version or not, is enough to handle what this was asking for. Since we have other issues/PRs open tracking those items, I'm going to close this issue.

**Closed as not planned by Eeems** 2023-08-18 01:56 UTC
Labels: documentation
