### ISSUE TITLE
bootstrap fails on line 96 while fetching standalone wget due to a TLS error

### ISSUE THREAD

**Issue by hunt529** [matteodelabre/toltec#422] opened 2021-08-29 18:00 UTC
Trying to install Totec

INFO:  Fetching secure wget
ERROR: Unexpected error on line bootstrap:96 in function wget-bootstrap
ERROR: This script failed to install. If you can't solve the above
       issue yourself, please report it at:
       
           <https://github.com/toltec-dev/toltec/issues>
       
       (Please also include these error logs to help solving the
       problem faster. Thank you!)
bootstrap: line 60: clean-path: command not found

Linux newbie -- any idea how to clear this one?

**Comment by matteodelabre** [comment] 2021-08-29 18:45
Hi @hunt529, the message you’re getting is a bit misleading, sorry about that! The actual error is on [line 96 of the bootstrap script](https://github.com/toltec-dev/toltec/blob/6fe6474e20004ba0fdd1e15e776739b9c159982e/scripts/bootstrap/bootstrap#L96), i.e. when fetching the wget binary. Can you please check that you’re connected to Wi-Fi? The bootstrap script needs an Internet connection to work.

**Comment by matteodelabre** [comment] 2021-08-29 19:19
~~Also, what is the system version of your device? This is the version number shown in the “General” settings panel.~~

**Comment by matteodelabre** [comment] 2021-08-29 21:04
I think the issue is that the latest nginx version, that I installed on the server this afternoon, broke compatibility with the native wget binary on the reMarkable. Could you confirm this by manually editing the `bootstrap` that you downloaded on your device (using `nano bootstrap`, for example)? You’d need to change line 84 and replace `https://` with `http://`, so that the whole line reads:

```sh
    local wget_remote=http://toltec-dev.org/thirdparty/bin/wget-v1.21.1
```

Once you’ve made that change, just run `bash bootstrap` to try installing again.

**Comment by moretea** [comment] 2021-08-30 16:33
I can confirm that this fixed this error message for me.

**Comment by hunt529** [comment] 2021-08-30 20:48
I can confirm that this fixed this error message for me.

**Comment by matteodelabre** [comment] 2021-08-30 21:16
Thank you both for testing. There is a fix in #423, just waiting for approval by the team.

**Comment by matteodelabre** [comment] 2021-09-02 12:46
A fix has just landed on the testing branch, and should reach the stable branch by next week. In the meantime, you can either  manually apply the diff from [my comment above](https://github.com/toltec-dev/toltec/issues/422#issuecomment-907872380) or download the [testing bootstrap script](https://raw.githubusercontent.com/toltec-dev/toltec/testing/scripts/bootstrap/bootstrap) and use it directly.

**Comment by siraben** [comment] 2021-09-23 02:51
I ran into this today, using the testing bootstrap script fixed the issue.

**Closed as completed** 2021-10-04 17:55 UTC
Labels: bug, install
